name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.6.0

      - name: Setup Node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # ✅ Install the Allure Playwright adapter (missing before)
      - name: Install Allure Playwright Adapter
        run: npm install -D allure-playwright

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Run Playwright tests with Allure
        run: |
          npx playwright test --project=${{ matrix.browser }}
        env:
          BASE_URL: https://conduit.bondaracademy.com
          PLAYWRIGHT_TRACE: retain-on-failure

      - name: Debug allure-results folder
        if: always()
        run: ls -R ./allure-results || echo "No allure-results found"

      - name: Generate Allure Report
        if: always()
        run: |
          allure generate ./allure-results --clean -o ./allure-report

      - name: Upload Allure Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ matrix.browser }}
          path: allure-report

      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright-report
