name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.6.0

      - name: Setup Node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          npx playwright test \
            --project=${{ matrix.browser }} \
            --workers=4 \
            --reporter=html \
            --reporter=github
        env:
          BASE_URL: https://conduit.bondaracademy.com
          PLAYWRIGHT_TRACE: retain-on-failure

      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright-report
